matrix:
 include:
  # Source package verification with Python 2.7 and librdkafka v0.11.5
  - os: linux
    language: python
    dist: trusty
    python: "2.7"
    env: LD_LIBRARY_PATH="$PWD/tmp-build/lib" LIBRDKAFKA_VERSION=v0.11.5
  # Source package verification with Python 3.6 and librdkafka v0.11.5
  - os: linux
    language: python
    dist: trusty
    python: "3.6"
    env: LD_LIBRARY_PATH="$PWD/tmp-build/lib" LIBRDKAFKA_VERSION=v0.11.5
  # Source package verification with Python 2.7 and librdkafka v0.11.5
  - os: osx
    python: "2.7"
    env: LD_LIBRARY_PATH="$PWD/tmp-build/lib" LIBRDKAFKA_VERSION=v0.11.5
    before_install:
        - brew update && brew upgrade pyenv
        - pyenv install -f 2.7.15
        - virtualenv -p ~/.pyenv/versions/2.7.15/bin/python ./env
        - source env/bin/activate
  # Source package verification with Python 3.6 and librdkafka v0.11.5
  - os: osx
    python: "3.6"
    env: LD_LIBRARY_PATH="$PWD/tmp-build/lib" LIBRDKAFKA_VERSION=v0.11.5
    before_install:
        - brew update && brew upgrade pyenv
        - pyenv install -f 3.6.5
        - virtualenv -p ~/.pyenv/versions/3.6.5/bin/python ./env
        - source env/bin/activate
  # cibuildwheel for osx
  - os: osx
    env: CIBW_BEFORE_BUILD="tools/bootstrap-librdkafka.sh --require-ssl v0.11.5 tmp" CFLAGS="-Itmp/include" LDFLAGS="-Ltmp/lib"
  # cibuildwheel for manylinux
  - os: linux
    dist: trusty
    sudo: required
    env: CIBW_BEFORE_BUILD="tools/prepare-cibuildwheel-linux.sh v0.11.5"
    language: python
    python: "2.7"
    services: docker

install:
 - if [[ $TRAVIS_OS_NAME == "osx" ]]; then python -m ensurepip && virtualenv /tmp/venv && source /tmp/venv/bin/activate ; fi
 - pip install -U pip
 - if [[ -z $CIBW_BEFORE_BUILD ]]; then pip install pytest-timeout flake8 ; fi
 - if [[ -z $CIBW_BEFORE_BUILD ]]; then rm -rf tmp-build ; tools/bootstrap-librdkafka.sh --require-ssl ${LIBRDKAFKA_VERSION} tmp-build ; fi
 - if [[ -n $TRAVIS_TAG && -n $CIBW_BEFORE_BUILD ]]; then pip install cibuildwheel; fi


script:
 - env
 - if [[ -z $CIBW_BEFORE_BUILD ]]; then pip install -v --global-option=build_ext --global-option="-Itmp-build/include/" --global-option="-Ltmp-build/lib" . .[avro] ; fi
 - if [[ -z $CIBW_BEFORE_BUILD ]]; then flake8 ; fi
 - if [[ -z $CIBW_BEFORE_BUILD ]]; then py.test -v --timeout 20 --ignore=tmp-build --import-mode append ; fi
 - if [[ -n $TRAVIS_TAG && -n $CIBW_BEFORE_BUILD ]]; then CIBW_ENVIRONMENT="TRAVIS_TAG='${TRAVIS_TAG}' TRAVIS_BUILD_NUMBER='${TRAVIS_BUILD_NUMBER}'" cibuildwheel --output-dir wheelhouse ; ls -la wheelhouse/ ; fi
 - if [[ -n $TRAVIS_TAG && $TRAVIS_OS_NAME == linux && -n $CIBW_BEFORE_BUILD ]]; then tools/test-manylinux.sh ; fi

deploy:
 provider: releases
 api_key:
  secure: UBqimO5uslvlA4UXENjIf9cXSZ+Cdt37cE18Xc4duP1wOHEnj2XyVumDALWw0HFvkrSbn2nFaJnkiClSB0lk6Z6yM6xG4W4MeNdKKGMjWwmSMfUCWX6jwrOYp0wDhN4fIeSqA5H+9AbZ8VIZkCMZU1YDk9QqLjIW5DXp5j9NzvzUfc7BxowLBXnpr+l3fQn96ZS3owbF9dq5AUoKatyhwOuip+9OBChyxJzRSATVqo3Gzay1h7m0za/ncxU4WlEETydzUA9/cxZ2T8+tUCFoQwVDXw/e2Ba/WCkFY4QZuLKfOOHQDPLfyn8SCqPKbjVgYLCfLG5+BnS/KLB5p2WQvgEpgw9VF/I+F+edIyKKlRfTVjBGlV4hEBsMc4YCEwpl1ydHAIsoeY2AGQ67u1sfhTAAS3CY8Vs4G9U5sfHKNMo3XanjY0JiofT3s1syoqqH3qIaMFpEte81+DAUbV6+c2S1aNVTOwKYuokEWyyl2qPQyYuzEmfj/+Ugd2N/NSgW+YtJ7YpXKgyIYqOVEUbIPAtHAxbX11mpr3TfsX/sozxj2ZQzRntPZ40KLZuJ/qNwFTyfFeScEzsnXJRGmRB25lZ3w5GPo0b1G9xAAqtn6FdCQeLXVJq9myJuLyeJyCpNt5Av8SahLVFR9yxKvIJcBy+M9GnYPLOi6lx/FmElX08=
 file_glob: true
 file: wheelhouse/*.whl
 skip_cleanup: true
 on:
  repo: csdisco/confluent-kafka-python
  tags: true
  condition: "-n $CIBW_BEFORE_BUILD"
